# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eb946f645b3ef67aa2e5ec20b14e7155d84ae38243e0109dbe05d1502f272c6139ff580fb987d57ee0e6486caa511b339465898653cf1c0ac5834464d2fbe44

test:
  secret_key_base: b2ea272213e0702639e17e63bd1d53fb92a15f5e1b01e67822b28eed08103df02ede9fd349a65154d7b354d2071a8460f1d8f59430deb10a9f21e3b2c9cd50cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1d4dd8dc1dc8190a97f2e0f840cf7b7e2c260a102dbf5fe3a20a3fdd0cca9246f214727e17ed1f55dbcdb60630245f12e39e43ac7c0b61ff7a92ef7f7dbac29e
